In [88]:
# import libraries for data manipulation
import numpy as np
import pandas as pd


In [3]:
# We can create matrices by converting lists of lists.

In [4]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# An Identity matrix is a square matrix in which all the elements of the 
# ...principal diagonal are ones and all other elements are zeros.

In [6]:
# An array can take the values of only one datatype.

In [7]:
# The following snippets of code are valid function(s) for NumPy

# A. numpy.cos(numpy.pi)
# B. numpy.sqrt(1.44)
# C. numpy.log(6)
# D. numpy.exp(4)

In [8]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [10]:
# If we change array 2, array 1 will also be impacted
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# we replace/change any value in an array?

In [12]:
# NumPy array can be saved on the disk for later use.

In [14]:
# The following code can be used to load a numpy array (matrix.npy is a data file)
# import numpy as np
# loaded_array = np.load('matrix.npy')

In [15]:
# I. A NumPy array can create a matrix with all entries of the same data type.

# II. In a Pandas DataFrame, each column can have its own data type.

In [16]:
# A data frame is made up of several series where each column is a series.

In [17]:
# A data frame can have columns of different data types?

In [18]:
# Pandas library of Python has functions for merging, sorting, and joining data frames.

In [19]:
# We can name each column of a data frame in Pandas.

In [21]:
# Statement: After executing the above code, either series1 will stack on top of series2 or 
# ...series2 will stack on top of series1.

##########
#df1 = pd.concat([series1,series2],axis=1)
##########

# the series will be combined side-by-side. When axis=0, two series will stack on each other
# ...when axis=1, two series will stack parallel to each other

In [22]:
# This function creates a dataframe
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [24]:
# this command is used to reset the index of a dataframe(df3)
# df3.reset_index()

In [25]:
# We have a data frame (df4), which contains the Name, Age, and Gender Columns. Now if we run the below code:
# df4.drop("Age",axis=1)
# Will the above code impact the original data frame (df4)?

# Answer: NO
# Because if you want to change the original dataframe then below code is to be used (add inplace=True)

# df.drop("Age",axis=1,inplace=True)

In [26]:
# The name of one the rows of a data frame "df" is "3rd Row". To print it, use...
# print(df.loc['3rd Row'])

# The name of one of the columns of a data frame "df" is "4th Column". To print it, use...
# print(df['4th Column'])

In [27]:
# merge() is a function in the Python library "Pandas", which provides standard database join operations 
# ...between DataFrame or named Series objects:

In [28]:
# Merging types...
# how=" outer"  - This will show the union values for "on" variable
# how= "inner" - This will show intersection(common entries ) values for "on" variable
# how="left" - This will show all the values of left dataframe (here in this question all the values of
# ...df1 will be reflected)
# how="right"- This will show all the values of right dataframe (here in this question all the values of 
# ...df2 will be reflected)

In [29]:
# merge() can be used for combining data on common columns

# concat() can be used for combining DataFrames across rows or columns.

In [30]:
# Given a dataframe(df1) with columns "Product" , "Age" and "Price". Which function will display the 
# ...unique values in the Product column.
# df1["Product"].unique()

In [31]:
# dataframe.groupby() function of the "Pandas" library performs one or more of the following steps:
# a) splits the data into groups based on some criteria
# b) applies a function to each category
# c) combines the result based on the applied function

In [32]:
# I. The apply() function of the "Pandas" library of Python, can be applied to both series and data frames.

# II. The apply() function of the "Pandas" library of Python, returns some value after passing each 
# ...row/column of a data frame with some function. The function can be both default and user-defined.

In [33]:
# I. Pandas Series.value_counts() function returns a Series containing counts of unique values.

# II. The resulting object will be in descending order so that the first element is the most 
# ...frequently-occurring element.

In [34]:
# to load csv file into the Jupyter Notebook?

# pd.read_csv()

In [35]:
# to save a dataframe(df2) as an excel file?

# df2.to_excel()

In [40]:
# to add 'hello'

l1 = ['learning', "Python", 'is fun?', True]
l1.append("hello")
l1

['learning', 'Python', 'is fun?', True, 'hello']

In [39]:
# to remove 'Python'
l2 = ['learning', "Python", 'is fun?', True]
l2.remove("Python")
l2

['learning', 'is fun?', True]

In [42]:
l1 = [1,2,3]
l2 = [4,5,6]
l1 + l2

[1, 2, 3, 4, 5, 6]

In [43]:
l1 = [2.0001, 3.908, 4.56]
sum(l1)

10.4681

In [45]:
def sum_3(a,b,c):
    d = a + b + c
    s = sum(d)
    return s
# Note that the inputs of the function must be lists. For example, the below code will return 17.
sum_3([1,2], [4,5], [2,3])

17

In [46]:
f = lambda x,y,z: x*y/z*z
f(1, 5, 78)

5.0

In [47]:
# will output all even numbers ranging from 1 to 100
set = [i for i in range(1,101) if i%2 == 0] 
print(set)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [49]:
# prints the length of each word
sentence = 'great learning is a great platform to learn about data science as it has great faculty and content.'
count = [len(i) for i in sentence.split()]
print(count)

[5, 8, 2, 1, 5, 8, 2, 5, 5, 4, 7, 2, 2, 3, 5, 7, 3, 8]


In [50]:
# will create a 2D identity matrix of size 2
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [52]:
# will create a 2D array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order
np.array([[9,8,7],[6,5,4],[3,2,1]])

# np.array() function helps to create arrays and matrices in python.
# The input for np.array() is a list of lists, where each list will work as a row of the matrix

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [54]:
# codes will add '1' to each element of d1, where d1 is
d1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
d2=d1 + 1
d2

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [58]:
# What will be the average value of all the elements in n6, where
n6 = np.matrix([[ 1, 4, 9, 121, 144, 169], 
[ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])
n6
n6.mean()

131.66666666666666

In [60]:
# What will be the dot product of n1 and n2, where

n1 = np.matrix([[121, 144, 169], 
[196, 225, 256], [ 289, 324, 361]])

n2 = np.matrix([[ 1, 4, 9], 
[ 1, 5, 4], [ 9, 4, 8]])

np.dot(n1, n2)

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [62]:
# what's the output
np.arange(20)[2:7] 

array([2, 3, 4, 5, 6])

In [69]:
# Which of the following command will reverse the array p, where
p = np.arange(20)
p[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [72]:
import numpy as np
demo_array = np.arange(0,10) 

demo_array
#demo_array <3
#demo_array[demo_array <6]
#np.max(demo_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# Vectors are 1 dimensional and matrices are 2 dimensional

In [75]:
# the following code would add a new column to a dataframe

#newcolumn = ["A", "B", "C", "D", "E"]
#dataframe['Alphabets'] = newcolumn

In [76]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [77]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [78]:
# axis 1 is for searching columns

In [81]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])

# When concatenating all Series along the index (axis=0), a Series is returned. When objs contains at least
# ...one DataFrame, a DataFrame is returned. When concatenating along the columns (axis=1), a DataFrame is 
# ...returned.

0    a
1    b
0    c
1    d
dtype: object

In [82]:
# to create a dataframe from external sources
# dataframe = pd.read_csv(‘filename’)

In [83]:
# to convert the list called 'football' into array
# np.array(football)

In [95]:
# read the data
df = pd.read_csv('Dateset_ODI.csv')
# returns the first 5 rows
df.head()

Scorecard       Team 1     Team 2       Winner     Margin        Ground  \
0   ODI # 1    Australia    England    Australia  5 wickets     Melbourne   
1   ODI # 2      England  Australia      England  6 wickets    Manchester   
2   ODI # 3      England  Australia    Australia  5 wickets        Lord's   
3   ODI # 4      England  Australia      England  2 wickets    Birmingham   
4   ODI # 5  New Zealand   Pakistan  New Zealand    22 runs  Christchurch   

     Match Date  
0   Jan 5, 1971  
1  Aug 24, 1972  
2  Aug 26, 1972  
3  Aug 28, 1972  
4  Feb 11, 1973

In [155]:
a = ['x', 'y', 'z']
b = ['w']
a.append(b)
print(a)

['x', 'y', 'z', ['w']]


In [153]:
a = ["apple", "banana", "cherry"]

b = ["Ford", "BMW", "Volvo"]

a.append(b)

print(a)

['apple', 'banana', 'cherry', ['Ford', 'BMW', 'Volvo']]


In [96]:
df.describe()

Scorecard     Team 1     Team 2     Winner     Margin   Ground  \
count         3932       3932       3932       3932       3753     3932   
unique        3932         24         25         25        227      173   
top     ODI # 1744  Australia  Sri Lanka  Australia  6 wickets  Sharjah   
freq             1        583        508        555        347      228   

         Match Date  
count          3932  
unique         3386  
top     Feb 4, 2007  
freq              6

In [101]:
df.max()

Scorecard       ODI # 999
Team 1           Zimbabwe
Team 2           Zimbabwe
Winner               tied
Ground          Worcester
Match Date    Sep 9, 2011
dtype: object

In [100]:
df['Ground'].max()

'Worcester'

In [111]:
df.groupby(['Ground'])['Scorecard'].count().sort_values(ascending=False)

Ground
Sharjah      228
Dhaka        156
Sydney       154
Melbourne    147
Harare       136
            ... 
Ballarat       1
Mackay         1
Devonport      1
Nairobi        1
Kwekwe         1
Name: Scorecard, Length: 173, dtype: int64

In [107]:
df.groupby(['Scorecard'])['Ground'].max().sort_values(ascending=True)

Scorecard
ODI # 3379      Aberdeen
ODI # 3381      Aberdeen
ODI # 3164      Aberdeen
ODI # 3491      Aberdeen
ODI # 2731      Aberdeen
                 ...    
ODI # 822     Wellington
ODI # 3232     Whangarei
ODI # 208      Worcester
ODI # 1446     Worcester
ODI # 1456     Worcester
Name: Ground, Length: 3932, dtype: object

In [139]:
# On which date 6 matches were played
# This solution provides accidental solution, because 6 matches in one day happen to be the max value
df.groupby(['Match Date'])['Scorecard'].count().sort_values(ascending=True)
# better solution is below...

Match Date
Apr 1, 1984     1
Mar 22, 2017    1
Mar 23, 1989    1
Mar 23, 1993    1
Mar 23, 1999    1
               ..
Jun 11, 1975    4
Jun 13, 1983    4
Jan 31, 2007    4
Jun 14, 1975    4
Feb 4, 2007     6
Name: Scorecard, Length: 3386, dtype: int64

In [141]:
# On which date 6 matches were played
# better solution than above
df['Match Date'].value_counts() # auto sorts by top/max value first

Feb 4, 2007     6
Jun 20, 1983    4
Jun 13, 1983    4
Jun 9, 1979     4
Jun 11, 1975    4
               ..
Aug 12, 1993    1
Feb 21, 1993    1
Jan 15, 2003    1
Nov 25, 1981    1
Jan 26, 1982    1
Name: Match Date, Length: 3386, dtype: int64

In [145]:
# Which team won maximum matches on Ground ‘ Sharjah’ ?

df_weekend = df[df.Ground=='Sharjah']
df_weekend.groupby(['Winner'])['Scorecard'].count().sort_values(ascending=False)

Winner
Pakistan        83
India           35
Sri Lanka       29
West Indies     19
Australia       14
South Africa    10
Afghanistan      9
New Zealand      9
England          8
Zimbabwe         8
tied             2
Canada           1
Netherlands      1
Name: Scorecard, dtype: int64

In [146]:
# Another way to solve the above
# Which team won maximum matches on Ground ‘ Sharjah’ ?

df1 = df[df['Ground'] == 'Sharjah']
df1['Winner'].value_counts()

Pakistan        83
India           35
Sri Lanka       29
West Indies     19
Australia       14
South Africa    10
Afghanistan      9
New Zealand      9
Zimbabwe         8
England          8
tied             2
Netherlands      1
Canada           1
Name: Winner, dtype: int64

In [142]:
# On which ground did Australia win the most number of matches?
df_winner = df[df.Winner=='Australia']
df_winner.groupby(['Ground'])['Scorecard'].count().sort_values(ascending=False)

Ground
Sydney        85
Melbourne     74
Adelaide      34
Perth         29
Brisbane      23
              ..
Faridabad      1
Georgetown     1
Hambantota     1
Jaipur         1
Worcester      1
Name: Scorecard, Length: 97, dtype: int64

In [144]:
# On which ground did Australia win the most number of matches?
# similar solution but better than above
df1 = df[df['Winner'] == 'Australia']  
df1['Ground'].value_counts()

Sydney         85
Melbourne      74
Adelaide       34
Perth          29
Brisbane       23
               ..
Chandigarh      1
Faridabad       1
Hambantota      1
Rajkot          1
Mumbai (BS)     1
Name: Ground, Length: 97, dtype: int64

In [137]:
# What is the number of times in which the winner was "Team 2"?
(df['Team 2'] == df['Winner']).sum()
# The use of count() would be inaccurate, because it was just count the number column entries...
# ...which would then provide the total number of records

1637

In [131]:
x = 1

for i in range(1,10,2):

    print(x*i)

1
3
5
7
9


In [132]:
a = np.array([['m', '2'],['n','3']])
a[0,1]

'2'