# NumPy Examples - Roman Dzadzic

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [5]:
print(np.cos(np.pi))
print(np.sqrt(4))
print(np.log(np.exp(5.2)))

-1.0
2.0
5.2


In [7]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T) # T = Transpose from rows to columns

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [14]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15) # arange = array range # exlusive of the last step (number 15 in this case)
print(vec2)
print('')
vec3 = np.arange(3,21,5)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  8 13 18]


In [19]:

vec4 = np.linspace(0,5,10) # in linspace, endpoint is inclusive
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped) # now stored as value
print(vec4) # still exists and stored

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [21]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5) # identity matrix
print('')
print("Mat 4:", mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Mat 4: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [28]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [34]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [35]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [45]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable (between 0 and 1)
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.38168869 0.17362335 0.05694662 0.84474323 0.18503158]
 [0.90579148 0.66379107 0.29859618 0.72897614 0.60551487]
 [0.77944666 0.42882678 0.65209904 0.41867761 0.43581577]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]

[[-1.97640733 -1.12237678 -1.80513162  1.55265973  0.13098416]
 [ 0.63638645  0.16100221  1.42035458  0.16653714 -0.7408978 ]
 [-1.22655367 -0.30827215 -0.00838035 -0.16312204  1.72409853]
 [ 0.74272306  0.69052716 -2.46882703 -0.20679059 -0.17115311]
 [ 0.09720438 -1.7656374   0.662477   -0.19837734  0.32676708]
 [-0.30162813  2.59372686  2.28288729  0.4049949  -0.95441183]
 [ 0.06642487  0.10852789 -1.34056459  0.79521463  1.19557428]
 [-1.23135498 -0.81689858 -0.25249843 -1.2944702  -1.00700304]
 [ 0.90963119  0.63745779 -2.13283321 -0.12969741 -0.62506995]
 [-0.13926652 -0.91183635  0.18743212 -0.10404218  0.37498969]]


In [46]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5296070276740322
1.0762482010136682


In [49]:
print(np.min(rand_mat))
print(np.min(rand_mat2))
print(np.max(rand_mat))
print(np.max(rand_mat2))

0.05694662134516992
-2.4688270265353154
0.9516416989564491
2.5937268633968413


In [ ]:
# break here for next video!

In [58]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(" ")
print(rand_vec[6])

[-0.65947546  0.77226021 -0.13413564 -1.31610327  1.03133643 -0.50011543
 -0.435009   -0.35304808  0.64098075 -2.16984683 -1.21576695  0.28145994
 -1.33764823  0.84629831 -0.85007179  1.12550899  0.59804947 -0.10963079
 -0.10055886]
 
-0.43500899941194276


In [59]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.03133643 -0.50011543 -0.435009   -0.35304808  0.64098075]


In [60]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.65947546 -1.31610327 -0.435009   -2.16984683 -1.33764823]


In [61]:
# what about matrices
print(rand_mat)
print(" ")
print(rand_mat[1][2])
print(" ")
print(rand_mat[1,2])


[[0.38168869 0.17362335 0.05694662 0.84474323 0.18503158]
 [0.90579148 0.66379107 0.29859618 0.72897614 0.60551487]
 [0.77944666 0.42882678 0.65209904 0.41867761 0.43581577]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]
 
0.29859618024842405
 
0.29859618024842405


In [62]:
print(rand_mat[0:2,1:3])

[[0.17362335 0.05694662]
 [0.66379107 0.29859618]]


In [63]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.65947546  0.77226021 -0.13413564 -1.31610327  1.03133643 -0.50011543
 -0.435009   -0.35304808  0.64098075 -2.16984683 -1.21576695  0.28145994
 -1.33764823  0.84629831 -0.85007179  1.12550899  0.59804947 -0.10963079
 -0.10055886]

[-0.65947546  0.77226021 -0.13413564  4.          4.         -0.50011543
 -0.435009   -0.35304808  0.64098075 -2.16984683 -1.21576695  0.28145994
 -1.33764823  0.84629831 -0.85007179  1.12550899  0.59804947 -0.10963079
 -0.10055886]

[-0.65947546  0.77226021 -0.13413564  1.          2.         -0.50011543
 -0.435009   -0.35304808  0.64098075 -2.16984683 -1.21576695  0.28145994
 -1.33764823  0.84629831 -0.85007179  1.12550899  0.59804947 -0.10963079
 -0.10055886]


In [69]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.38168869 0.17362335 0.05694662 0.84474323 0.18503158]
 [0.90579148 0.66379107 0.29859618 0.         0.        ]
 [0.77944666 0.42882678 0.65209904 0.         0.        ]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]

[[0.38168869 0.17362335 0.05694662 0.84474323 0.18503158]
 [0.90579148 0.66379107 0.29859618 0.         0.        ]
 [0.77944666 0.42882678 0.65209904 0.         0.        ]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]


In [70]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.38168869 0.17362335 0.05694662]
 [0.90579148 0.66379107 0.29859618]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [71]:
print(rand_mat)

[[3.         3.         3.         0.84474323 0.18503158]
 [3.         3.         3.         0.         0.        ]
 [0.77944666 0.42882678 0.65209904 0.         0.        ]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]


In [72]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.84474323 0.18503158]
 [3.         3.         3.         0.         0.        ]
 [0.77944666 0.42882678 0.65209904 0.         0.        ]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]


In [ ]:
# break here for next video

In [82]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print('')
print(rand_vec>0)
print('')
print(rand_vec[rand_vec>0])

[-0.21550084  0.06183872 -1.0359988   0.36980944 -0.30354839  2.06108429
 -0.26466732  0.52025245  1.00915045 -1.05314332  0.57133748  1.15196548
  1.40619005  0.45287798  0.5364048 ]

[False  True False  True False  True False  True  True False  True  True
  True  True  True]

[0.06183872 0.36980944 2.06108429 0.52025245 1.00915045 0.57133748
 1.15196548 1.40619005 0.45287798 0.5364048 ]


In [86]:
print(rand_mat2)
print('')
print(rand_mat2>0)
print('')
print(rand_mat2[rand_mat2>0])
print('')
print(rand_mat2)

[[-1.97640733 -1.12237678 -1.80513162  1.55265973  0.13098416]
 [ 0.63638645  0.16100221  1.42035458  0.16653714 -0.7408978 ]
 [-1.22655367 -0.30827215 -0.00838035 -0.16312204  1.72409853]
 [ 0.74272306  0.69052716 -2.46882703 -0.20679059 -0.17115311]
 [ 0.09720438 -1.7656374   0.662477   -0.19837734  0.32676708]
 [-0.30162813  2.59372686  2.28288729  0.4049949  -0.95441183]
 [ 0.06642487  0.10852789 -1.34056459  0.79521463  1.19557428]
 [-1.23135498 -0.81689858 -0.25249843 -1.2944702  -1.00700304]
 [ 0.90963119  0.63745779 -2.13283321 -0.12969741 -0.62506995]
 [-0.13926652 -0.91183635  0.18743212 -0.10404218  0.37498969]]

[[False False False  True  True]
 [ True  True  True  True False]
 [False False False False  True]
 [ True  True False False False]
 [ True False  True False  True]
 [False  True  True  True False]
 [ True  True False  True  True]
 [False False False False False]
 [ True  True False False False]
 [False False  True False  True]]

[1.55265973 0.13098416 0.63638645 0.

In [87]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.21550084  0.06183872 -1.0359988   0.36980944 -0.30354839  2.06108429
 -0.26466732  0.52025245  1.00915045 -1.05314332  0.57133748  1.15196548
  1.40619005  0.45287798  0.5364048 ]

[-0.21550084  0.06183872 -1.0359988   0.36980944 -0.30354839 -5.
 -0.26466732 -5.         -5.         -1.05314332 -5.         -5.
 -5.          0.45287798 -5.        ]


In [88]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [89]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [90]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-1.97640733 -1.12237678 -1.80513162  1.55265973  0.13098416]
 [ 0.63638645  0.16100221  1.42035458  0.16653714 -0.7408978 ]
 [-1.22655367 -0.30827215 -0.00838035 -0.16312204  1.72409853]
 [ 0.74272306  0.69052716 -2.46882703 -0.20679059 -0.17115311]
 [ 0.09720438 -1.7656374   0.662477   -0.19837734  0.32676708]
 [-0.30162813  2.59372686  2.28288729  0.4049949  -0.95441183]
 [ 0.06642487  0.10852789 -1.34056459  0.79521463  1.19557428]
 [-1.23135498 -0.81689858 -0.25249843 -1.2944702  -1.00700304]
 [ 0.90963119  0.63745779 -2.13283321 -0.12969741 -0.62506995]
 [-0.13926652 -0.91183635  0.18743212 -0.10404218  0.37498969]]



In [92]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])
print('')
new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.84474323 0.18503158]
 [3.         3.         3.         0.         0.        ]
 [0.77944666 0.42882678 0.65209904 0.         0.        ]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]

[[-1.97640733 -1.12237678 -1.80513162  1.55265973  0.13098416]
 [ 0.63638645  0.16100221  1.42035458  0.16653714 -0.7408978 ]
 [-1.22655367 -0.30827215 -0.00838035 -0.16312204  1.72409853]
 [ 0.74272306  0.69052716 -2.46882703 -0.20679059 -0.17115311]
 [ 0.09720438 -1.7656374   0.662477   -0.19837734  0.32676708]
 [-0.30162813  2.59372686  2.28288729  0.4049949  -0.95441183]
 [ 0.06642487  0.10852789 -1.34056459  0.79521463  1.19557428]
 [-1.23135498 -0.81689858 -0.25249843 -1.2944702  -1.00700304]
 [ 0.90963119  0.63745779 -2.13283321 -0.12969741 -0.62506995]
 [-0.13926652 -0.91183635  0.18743212 -0.10404218  0.37498969]]

[[3.         3.         3.         0.84474323 0.18503158]
 [3.         3.   

In [94]:
# we can also save/load as text files...but only single variables
np.savetxt('romans_text_file_name.txt',rand_mat,delimiter='|')
rand_mat_txt = np.loadtxt('romans_text_file_name.txt',delimiter='|')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.84474323 0.18503158]
 [3.         3.         3.         0.         0.        ]
 [0.77944666 0.42882678 0.65209904 0.         0.        ]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]

[[3.         3.         3.         0.84474323 0.18503158]
 [3.         3.         3.         0.         0.        ]
 [0.77944666 0.42882678 0.65209904 0.         0.        ]
 [0.9516417  0.94595705 0.66476337 0.44784091 0.14951701]
 [0.70170802 0.87889079 0.27389066 0.28121928 0.38517781]]


In [50]:
vec = np.arange(10, 20, 3)
print(vec)

[10 13 16 19]


In [51]:
vec=np.linspace(10,20,3)
print(vec)

[10. 15. 20.]


In [53]:
vec1 = np.arange(0, 12)
print(vec1)
vec2 = vec1.reshape(4, 3)
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
import numpy as np
arr = np.arange(4, 20, 5)
print(arr)

[ 4  9 14 19]


In [79]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [80]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1+1
print(array1)
print('')
print(array2)
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [96]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]
